version: '3.9'
services:
  minoria_prod:
    container_name: minoria_prod
    image: postgres:15.0
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=100'
      - '-c'
      - 'shared_buffers=1GB'
      - '-c'
      - 'effective_cache_size=4GB'
      - '-c'
      - 'work_mem=16MB'
      - '-c'
      - 'maintenance_work_mem=512MB'
      - '-c'
      - 'random_page_cost=1.1'
      - '-c'
      - 'temp_file_limit=10GB'
      - '-c'
      - 'log_min_duration_statement=200ms'
      - '-c'
      - 'idle_in_transaction_session_timeout=10s'
      - '-c'
      - 'lock_timeout=1s'
      - '-c'
      - 'statement_timeout=60s'
      - '-c'
      - 'shared_preload_libraries=pg_stat_statements'
      - '-c'
      - 'pg_stat_statements.max=10000'
      - '-c'
      - 'pg_stat_statements.track=all'
    environment:
      POSTGRES_DB: minoria_prod
      POSTGRES_USER: minoria
      POSTGRES_PASSWORD: IeNfzx5vg
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ../InitDb:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U minoria -d minoria_prod']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - app
    labels:
      org.label-schema.group: 'application'

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - 6379:6379
      - 8002:8001
    networks:
      - app
    labels:
      org.label-schema.group: 'application'
      
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9023:9000
      - 36713:36713
    environment:
      MINIO_ROOT_USER: minoria
      MINIO_ROOT_PASSWORD: IeNfzx5vg
    restart: unless-stopped
    networks:
      - app
    labels:
      org.label-schema.group: 'application'
    command: server --console-address ":36713" /export
    volumes:
      - ../minio/data:/export
      - ../minio/config:/root/.minio
    healthcheck:
      test: ["CMD", "curl", "-k", "http://minio:9000/minio/health/live"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 5s

networks:
  app:
    name: app
    driver: bridge
