version: 3

# Usage of first_deploy:
# task first_deploy REPO=<REPO> BRANCH=<BRANCH>
#
# Usage of deploy:
# task deploy REPO=<REPO> BRANCH=<BRANCH>
#
# Usage of rename:
# task rename

tasks:
  first_deploy:
    dir: DevOps/playbooks
    cmds:
      - wsl -d Ubuntu bash -c 'export ANSIBLE_CONFIG=$PWD/ansible.cfg && cd $PWD && /home/artem/.local/bin/ansible-playbook first_deploy.yml -e REPO="https://github.com/LowArtem/MinoriaBackend.git" -e BRANCH="master"'

  deploy:
    dir: DevOps/playbooks
    cmds:
      - wsl -d Ubuntu bash -c 'export ANSIBLE_CONFIG=$PWD/ansible.cfg && cd $PWD && /home/artem/.local/bin/ansible-playbook deploy.yml -e REPO="https://github.com/LowArtem/MinoriaBackend.git" -e BRANCH="master"'
        
  update:
    dir: DevOps/playbooks
    cmds:
      - wsl -d Ubuntu bash -c 'export ANSIBLE_CONFIG=$PWD/ansible.cfg && cd $PWD && /home/artem/.local/bin/ansible-playbook update.yml -e REPO="https://github.com/LowArtem/MinoriaBackend.git" -e BRANCH="master"'
      